//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QD_Tour_Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour_Price
    {
        public string Id { get; set; }
        public System.DateTime Date { get; set; }
        public string ID_Tour { get; set; }
        public decimal Price { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
