//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QD_Tour_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomTour
    {
        public string Id { get; set; }
        public string Message { get; set; }
        public string MemberId { get; set; }
        public Nullable<int> IsPaid { get; set; }
        public Nullable<System.DateTime> MessageSentTime { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
