//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QD_Tour_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Golf_Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Golf_Package()
        {
            this.Golf_Reservation = new HashSet<Golf_Reservation>();
        }
    
        public string Id { get; set; }
        public string Golf_Id { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
    
        public virtual Golf Golf { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Golf_Reservation> Golf_Reservation { get; set; }
    }
}
