//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QD_Tour_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Price
    {
        public string Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> SingleRoomPrice { get; set; }
        public Nullable<decimal> DoulbeRoomPrice { get; set; }
        public Nullable<decimal> OtherRoomPrice { get; set; }
        public string ID_Hotel { get; set; }
        public Nullable<int> CanReserve { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
