//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QD_Tour_Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel_Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel_Package()
        {
            this.Hotel_Reservation = new HashSet<Hotel_Reservation>();
        }
    
        public string Id { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public string Country { get; set; }
        public string Area { get; set; }
        public string ID_Hotel { get; set; }
        public string SingRommPhoto { get; set; }
        public string DoubleRoomPhoto { get; set; }
        public string OtherRoomPhoto { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel_Reservation> Hotel_Reservation { get; set; }
    }
}
